apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dev
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-dev
  template:
    metadata:
      labels:
        app: mongodb-dev
    spec:
      containers:
      - name: mongodb
        image: gcr.io/$PROJECT_ID/bookstore-mongo:latest
        ports:
        - containerPort: 27017